# Generated by Django 3.1 on 2020-09-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayModel',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
            ],
        ),
    ]
