# Generated by Django 3.1 on 2020-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatewaymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gatewaymodel',
            name='price',
        ),
        migrations.AddField(
            model_name='gatewaymodel',
            name='company',
            field=models.CharField(blank=True, db_column='COMPANY', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gatewaymodel',
            name='page',
            field=models.IntegerField(blank=True, db_column='PAGE', null=True),
        ),
    ]
