# Generated by Django 3.1.3 on 2020-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20200908_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_code', models.CharField(db_column='COMPANY_CODE', max_length=6, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='COMPANY_NAME', max_length=30)),
                ('starred', models.CharField(db_column='STARRED', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DailyInfoForCompany',
            fields=[
                ('company_code', models.CharField(db_column='COMPANY_CODE', max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='DATE')),
                ('opening_price', models.IntegerField(db_column='OPENING_PRICE')),
                ('closing_price', models.IntegerField(db_column='CLOSING_PRICE')),
                ('highest_price', models.IntegerField(db_column='HIGHEST_PRICE')),
                ('lowest_price', models.IntegerField(db_column='LOWEST_PRICE')),
                ('volume', models.IntegerField(db_column='VOLUME')),
            ],
        ),
        migrations.DeleteModel(
            name='GatewayModel',
        ),
    ]
